### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by simonravel** [actions-on-google/apiai-transactions-nodejs#20]
I followed every step and in the last step (node order-update.js ), I get this error:

Status: 404 Not Found
`{ error:
   { code: 404,
     message: 'Requested entity was not found.',
     status: 'NOT_FOUND' } }`

**Comment by taycaldwell** [comment]
Hi Simon,

The 404 message indicates that the entity you are trying to update was not found. Are you providing a valid unique order ID for an existing order before making the update order request?

**Comment by simonravel** [comment]
Hi Taylor,

I don't know where to find those IDs...

**Comment by taycaldwell** [comment]
Hello @simonravel,

The sample generates a random unique ID for an order: https://github.com/actions-on-google/dialogflow-transactions-nodejs/blob/master/functions/index.js#L126

You can modify this line in the code and give it your own ID.

Once you know the ID of the order, you can update the order update script with this ID here:
https://github.com/actions-on-google/dialogflow-transactions-nodejs/blob/master/functions/order-update.js#L52

and run the script to make the update order request.

Hopefully this helps!

**Comment by simonravel** [comment]
I changed both to '17', but I got the same error.
Do I need to deploy the code first to firebase to make it work?

**Comment by simonravel** [comment]
@taycaldwell
Since it is the POST request to the Actions API that returns this error message, should this number then also be stored somewhere there?

**Comment by simonravel** [comment]
@taycaldwell 
Can you please provide some feedback on this issue? I need to implement the Transaction API for an action where different sessions can be booked. Even though, it is for free, Google says that the Transaction APi is required

**Comment by taycaldwell** [comment]
@simonravel 

You will need to ask the user to make a [TransactionDecision](https://github.com/actions-on-google/dialogflow-transactions-nodejs/blob/master/functions/index.js#L282) with a proposed order that has an [order ID](https://github.com/actions-on-google/dialogflow-transactions-nodejs/blob/master/functions/index.js#L129) that uniquely identifies that order.

Once the user confirms the transaction and the [order is accepted](https://github.com/actions-on-google/dialogflow-transactions-nodejs/blob/master/functions/index.js#L129), you can submit a [OrderUpdate](https://github.com/actions-on-google/dialogflow-transactions-nodejs/blob/master/functions/index.js#L333) to create the order. 

Once the order is created, you can use the [order-update.js script to submit a POST request to update the order's status](https://github.com/actions-on-google/dialogflow-transactions-nodejs/blob/master/functions/order-update.js#L52) using the unique order ID.

If you receive a 404, the order is not found and thus never created.

Please make sure the Actions API is enabled for your project, and you are creating an order before using the order-update.js script to send a POST request to update the order via the Actions API.

**Comment by simonravel** [comment]
@taycaldwell 
Thanks a lot! That makes things a lot more clear. But how do you invoke the TransactionDecision intent, since there are no training phrases specified? Is this intent automatically invoked after the Transaction Merchant or the Transaction Google?

The test app always crashes after those intents.
![Schermafbeelding 2019-06-29 om 12 15 31](https://user-images.githubusercontent.com/34872269/60382734-c2155e00-9a67-11e9-8f71-7efcd6c9478f.png)

**Comment by simonravel** [comment]
@taycaldwell,
can you help me further?

**Comment by taycaldwell** [comment]
Hello @simonravel,

This sample has been updated to use the new Transactions API flow.

Please make sure:

- The Transactions API is enabled for your project (This can be found in the Directory Information tab of the Actions on Google Console)
- A privacy policy is provided for your project (This can be found in the Directory Information tab of the Actions on Google Console)
- If sending Order Updates, the Actions API is enabled for your project. (This can be found in the GCP API Library, please refer to the README of this repository for more information)
- The account you are testing the flow on meets all the transaction requirements needed for the flow you are testing. (i.e. has Google Pay payment information, delivery address, etc.)


Because the sample has been updated to use the new recommended Transactions API flow, I will be closing this issue as obsolete.

If you run into any other issues, feel free to re-open the issue, or start a new issue.
