### ISSUE TITLE
Sample code gives 'Sorry, something went wrong' after Confirm Transaction

### ISSUE THREAD

**Issue by dzolnai** [actions-on-google/apiai-transactions-nodejs#22]
Hello,

I've deployed this sample to a new DialogFlow + Actions On Google project, following the steps in the guideline.
When I select any payment type, select my delivery address, and in the end confirm the transaction, I get a _'Sorry, something went wrong. Please try again later'_ error message.
I have tried on device and also in the emulator.
I can't find any error in the StackDriver logs, nor in the emulator logs. The last event I see is a 200 OK response with the transaction decision intent containing the order details.

I have:
- [x] Added a privacy policy link
- [x] Checked that I serve physical goods from my app

**Comment by pragnakalpdev** [comment]
We are also facing the same issue. Did you find any solution?

**Comment by dzolnai** [comment]
No. The problem is, this happens with our own production app too, not only with the sample project.

**Comment by pragnakalpdev** [comment]
Yes, same here.
We tried in the production too and not working there as well.

As per https://github.com/actions-on-google/dialogflow-transactions-nodejs/issues/15 we have already filled up all the required information under Directory Information. 

In the tokenizationParameters, instead of:

```
tokenizationParameters: {
// Tokenization parameter data will be provided by a
// payment processor, i.e. Stripe, Braintree, Vantiv, etc.
parameters: {
'gateway': 'braintree',
'braintree:sdkVersion': '1.4.0',
'braintree:apiVersion': 'v1',
'braintree:merchantId': 'xxxxxxxxxxx',
'braintree:clientKey': 'sandbox_xxxxxxxxxxxxxxx',
'braintree:authorizationFingerprint': 'sandbox_xxxxxxxxxxxxxxx',
},
```
we have tried our own payment gateway and also example:

```
tokenizationParameters: {
// Tokenization parameter data will be provided by a
// payment processor, i.e. Stripe, Braintree, Vantiv, etc.
parameters: {
'gateway': 'example',
'gatewayMerchantId': 'examplegatewayMerchantId'
},
```

but that doesn't work either.

**Comment by taycaldwell** [comment]
Hello @dzolnai and @pragnakalpdev,

This sample has been updated with the new recommended Transactions API flow. Please update your code to use this new flow.

With that said, in order to complete the transactions flow please make sure:

- The Transactions API is enabled for your project (This can be found in the Directory Information tab of the Actions on Google Console)
- A privacy policy is provided for your project (This can be found in the Directory Information tab of the Actions on Google Console)
- If sending Order Updates, the Actions API is enabled for your project. (This can be found in the GCP API Library, please refer to the README of this repository for more information)
- The account you are testing the flow on meets all the transaction requirements needed for the flow you are testing. (i.e. has Google Pay payment information, delivery address, etc.)
- If you are testing the transactions flow outside of sandbox orders, ensure you are registered as a merchant with GPay.

**Comment by dzolnai** [comment]
Hello @taycaldwell ,

I can confirm that it is working now as expected.
It took me some time to get my own app working with transactions again, if the order JSON has one mistake, the app will just crash without any pointers to the cause.
It would be great for the future if you could add better logging, like switching the assistant on an Android device in debug mode, and it would print a stack trace or something like that on a crash, or even if the simulator would give actual errors on such crashes.
